name: Publish mullvad-socks5-urls.txt

on:
  repository_dispatch:
  workflow_dispatch:
  push:
  schedule:
    - cron: 0 0 * * *

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
  
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Clone and setup repo
      run: |
        git clone "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" repo
        cd repo
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git checkout result
        git pull
        echo "TAG_NAME=$(date +"%Y-%m-%dT%H-%M-%S")" >> $GITHUB_ENV
        pip3 install -r requirements.txt
        python3 generator.py
        ls
        git add .
        git commit -m "update result"
        git push -u origin result
