name: Publish mullvad-socks5-urls.txt

on:
  repository_dispatch:
  workflow_dispatch:
  push:
  schedule:
    - cron: 0 0 * * *

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
  
    steps:
      - uses: actions/checkout@v4
        with:
          ref: result    # Checkout the result branch directly
          fetch-depth: 0 # Needed for full git history if required

      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Configure git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Generate file
        env:
          MULLVAD_API_URL: ${{ secrets.MULLVAD_API_URL }}
        run: |
          pip install -r requirements.txt
          python generator.py

      - name: Commit and push changes
        run: |
          git add .
          git diff-index --quiet HEAD || git commit -m "update result"
          git push origin result
